name: swinfire
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aiohappyeyeballs=2.4.3
  - aiosignal=1.3.1
  - airflow=2.9.2
  - alembic=1.14.0
  - anyio=4.6.2.post1
  - aom=3.3.0
  - apache-airflow=2.9.2
  - apache-airflow-providers-common-compat=1.2.2
  - apache-airflow-providers-common-io=1.4.2
  - apache-airflow-providers-common-sql=1.20.0
  - apache-airflow-providers-fab=1.5.1
  - apache-airflow-providers-ftp=3.11.1
  - apache-airflow-providers-http=4.13.3
  - apache-airflow-providers-imap=3.7.0
  - apache-airflow-providers-smtp=1.8.1
  - apache-airflow-providers-sqlite=3.9.1
  - apispec=6.7.1
  - argcomplete=3.5.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asciitree=0.3.3
  - asgiref=3.8.1
  - attrs=24.2.0
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.29
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.19
  - aws-c-mqtt=0.10.7
  - aws-c-s3=0.6.7
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.16.0
  - backoff=1.11.1
  - bcrypt=4.2.1
  - billiard=4.2.0
  - blas=2.125
  - blas-devel=3.9.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.6.1
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.9.24
  - cached-property=1.5.2
  - cachelib=0.9.0
  - cachetools=5.5.0
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfitsio=4.4.1
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - clickclick=20.10.2
  - cligj=0.7.2
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - colorlog=4.8.0
  - colour=0.1.5
  - configobj=5.0.9
  - configupdater=3.2
  - connexion=2.14.2
  - contourpy=1.3.1
  - cron-descriptor=1.4.5
  - croniter=5.0.1
  - cryptography=43.0.3
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - cytoolz=1.0.0
  - dask=2024.11.2
  - dask-core=2024.11.2
  - dask-expr=1.1.19
  - deprecated=1.2.15
  - dill=0.3.9
  - distributed=2024.11.2
  - dnspython=2.7.0
  - docutils=0.21.2
  - donfig=0.8.1.post1
  - earthengine-api=0.1.406
  - easydict=1.9
  - einops=0.8.0
  - email-validator=2.2.0
  - exceptiongroup=1.2.2
  - expat=2.7.3
  - fasteners=0.17.3
  - ffmpeg=5.0.1
  - filelock=3.13.1
  - fiona=1.9.6
  - flask=2.2.5
  - flask-appbuilder=4.5.2
  - flask-babel=2.0.0
  - flask-caching=2.3.0
  - flask-limiter=3.8.0
  - flask-login=0.6.3
  - flask-session=0.5.0
  - flask-sqlalchemy=2.5.1
  - flask-wtf=1.2.2
  - fmt=11.0.2
  - folium=0.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - furl=2.1.3
  - gdal=3.9.2
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geos=3.12.2
  - geotiff=1.7.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-api-core=2.22.0
  - google-api-python-client=2.154.0
  - google-auth=2.36.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.18.2
  - google-crc32c=1.5.0
  - google-re2=1.1.20240702
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.66.0
  - greenlet=3.1.1
  - gunicorn=23.0.0
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - heapdict=1.0.1
  - hpack=4.0.0
  - httpcore=1.0.7
  - httplib2=0.22.0
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - infinity=1.5
  - inflection=0.5.1
  - intervals=0.9.2
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - json-c=0.17
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - kealib=1.5.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-object-proxy=1.10.0
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.10.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.21
  - libdrm=2.4.123
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgdal=3.9.2
  - libgdal-core=3.9.2
  - libgdal-fits=3.9.2
  - libgdal-grib=3.9.2
  - libgdal-hdf4=3.9.2
  - libgdal-hdf5=3.9.2
  - libgdal-jp2openjpeg=3.9.2
  - libgdal-kea=3.9.2
  - libgdal-netcdf=3.9.2
  - libgdal-pdf=3.9.2
  - libgdal-pg=3.9.2
  - libgdal-postgisraster=3.9.2
  - libgdal-tiledb=3.9.2
  - libgdal-xls=3.9.2
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.3
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.28
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libspatialindex=2.0.0
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libtorch=2.3.1
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.21.0
  - libvpx=1.11.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.11.2
  - libzlib=1.3.1
  - limits=3.13.0
  - linkify-it-py=2.0.3
  - llvm-openmp=21.1.8
  - locket=1.0.0
  - lockfile=0.12.2
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.3.6
  - mapclassify=2.8.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - marshmallow=3.23.1
  - marshmallow-oneofschema=3.1.1
  - marshmallow-sqlalchemy=0.28.2
  - matplotlib-base=3.9.2
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - methodtools=0.4.7
  - minizip=4.0.7
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - monai=1.3.2
  - more-itertools=10.5.0
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - munkres=1.1.4
  - nccl=2.27.3.1
  - ncurses=6.5
  - netcdf4=1.7.1
  - nettle=3.7.3
  - networkx=3.2.1
  - nspr=4.36
  - nss=3.104
  - numcodecs=0.14.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openblas=0.3.28
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=2.0.2
  - ordered-set=4.1.0
  - orderedmultidict=1.0.1
  - packaging=24.2
  - pandas=2.2.2
  - partd=1.4.2
  - passlib=1.7.4
  - pathspec=0.12.1
  - pcre2=10.44
  - pendulum=3.0.0
  - phonenumbers=8.13.50
  - pillow=10.3.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pooch=1.8.2
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - prison=0.2.1
  - proj=9.4.1
  - propcache=0.2.0
  - proto-plus=1.25.0
  - psutil=6.1.0
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pygments=2.18.0
  - pyjwt=2.10.0
  - pykdtree=1.3.13
  - pyopenssl=24.2.1
  - pyorbital=1.8.3
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pyresample=1.31.0
  - pysocks=1.7.1
  - pyspectral=0.13.5
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-geotiepoints=1.7.5
  - python-lmdb=1.5.1
  - python-nvd3=0.16.0
  - python-slugify=8.0.4
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - rasterio=1.3.11
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rich=13.9.4
  - rich-argparse=1.6.0
  - rioxarray=0.15.5
  - rpds-py=0.21.0
  - rsa=4.9.1
  - rtree=1.3.0
  - s2n=1.5.5
  - satpy=0.49.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setproctitle=1.3.4
  - setuptools=75.1.0
  - shapely=2.0.6
  - six=1.16.0
  - sleef=3.9.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - spdlog=1.14.1
  - sqlalchemy=1.4.54
  - sqlalchemy-utils=0.41.2
  - sqlite=3.46.0
  - sqlparse=0.5.2
  - svt-av1=1.1.0
  - sympy=1.13.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tblib=3.0.0
  - tenacity=9.0.0
  - termcolor=2.5.0
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tiledb=2.25.0
  - time-machine=2.16.0
  - tk=8.6.13
  - toolz=1.0.0
  - torchaudio=2.3.1
  - torchinfo=1.8.0
  - tornado=6.4.1
  - tqdm=4.67.1
  - trollimage=1.26.0
  - trollsift=0.5.1
  - tzcode=2024b
  - tzdata=2024b
  - uc-micro-py=1.0.3
  - unicodecsv=0.14.1
  - unicodedata2=15.1.0
  - universal_pathlib=0.2.5
  - uriparser=0.9.8
  - uritemplate=4.1.1
  - urllib3=2.2.1
  - werkzeug=2.2.3
  - wheel=0.44.0
  - wirerope=0.4.8
  - wrapt=1.17.0
  - wtforms=3.2.1
  - x264=1!161.3030
  - x265=3.5
  - xarray=2024.11.0
  - xerces-c=3.2.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zarr=2.18.3
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - aiohttp==3.10.11
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - flask-jwt-extended==4.7.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.68.0
      - hf-xet==1.2.0
      - huggingface-hub==1.4.1
      - importlib-metadata==8.5.0
      - modelscope==1.34.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.13.0.92
      - opentelemetry-api==1.28.2
      - opentelemetry-exporter-otlp==1.28.2
      - opentelemetry-exporter-otlp-proto-common==1.28.2
      - opentelemetry-exporter-otlp-proto-grpc==1.28.2
      - opentelemetry-exporter-otlp-proto-http==1.28.2
      - opentelemetry-proto==1.28.2
      - opentelemetry-sdk==1.28.2
      - opentelemetry-semantic-conventions==0.49b2
      - protobuf==5.28.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-daemon==3.1.0
      - regex==2026.1.15
      - safetensors==0.7.0
      - seaborn==0.13.2
      - sentry-sdk==2.51.0
      - shellingham==1.5.4
      - simple-file-checksum==1.2.2
      - smmap==5.0.2
      - socksio==1.0.0
      - sqlalchemy-jsonfield==1.0.2
      - timm==1.0.24
      - tokenizers==0.22.2
      - torch==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - transformers==5.1.0
      - typer==0.23.1
      - typer-slim==0.23.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - wandb==0.24.1
