#!/usr/bin/env python3
"""Materialize this project's locked TS-SatFire active-fire partition.

Training and validation follow the pinned upstream ROI logic.  At the user's
direction, the authoritative test cohort is the 24 ``US_2021_*`` units present
in ``dataset_test`` rather than the upstream generator's 17 named-fire labels.
This deliberate project-level choice is explicit and versioned here.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ROI_DIR = PROJECT_ROOT / "roi"
SPLIT_DIR = PROJECT_ROOT / "splits"
UPSTREAM_SHA = "da7573219967edfe17e317310b66fd8a913f4a2e"

VALIDATION_IDS = (
    "20568194", "20701026", "20562846", "20700973", "24462610", "24462788",
    "24462753", "24103571", "21998313", "21751303", "22141596", "21999381",
    "22712904",
)
ACTIVE_FIRE_TEST_IDS = (
    "US_2021_MT4714310953420211004",
    "US_2021_ID4558511544420210705",
    "US_2021_ID4663811466720210707",
    "US_2021_MT4568311385420210708",
    "US_2021_ID4453211532920210810",
    "US_2021_ID4762711608320210708",
    "US_2021_WA4879111827120210805",
    "US_2021_WA4828511853120210713",
    "US_2021_WA4856812048820210708",
    "US_2021_WA4877811903420210803",
    "US_2021_MT4579011310120210708",
    "US_2021_CA3568711855020210818",
    "US_2021_CA3604711863120210910",
    "US_2021_CA3627811855020210815",
    "US_2021_CA3658211879520210912",
    "US_2021_CA4086312235520210630",
    "US_2021_NM3344410803520210514",
    "US_2021_CA3451712013120211011",
    "US_2021_AZ3368910927620210616",
    "US_2021_AZ3345510938920210616",
    "US_2021_NM3676810505920211120",
    "US_2021_NM3323810847220210520",
    "US_2021_NM3340210587120210426",
    "US_2021_FL2521008104520210308",
)


def _id_sort_key(value: str) -> tuple[int, str]:
    return (0, f"{int(value):012d}") if value.isdigit() else (1, value)


def load_train_source_ids() -> list[str]:
    ids: list[str] = []
    for year in ("2017", "2018", "2019", "2020"):
        source = ROI_DIR / f"us_fire_{year}_out_new.csv"
        if not source.is_file():
            raise FileNotFoundError(f"Required official ROI source is missing: {source}")
        with source.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if "Id" not in (reader.fieldnames or []):
                raise ValueError(f"ROI source lacks the 'Id' column: {source}")
            ids.extend(row["Id"].strip() for row in reader if row["Id"].strip())
    if len(ids) != len(set(ids)):
        raise ValueError("The 2017–2020 ROI sources contain duplicate event IDs.")
    missing_validation = sorted(set(VALIDATION_IDS) - set(ids))
    if missing_validation:
        raise ValueError(f"Validation IDs absent from local ROI files: {missing_validation}")
    return sorted(ids, key=_id_sort_key)


def write_manifest(path: Path, event_ids: tuple[str, ...] | list[str], purpose: str) -> None:
    header = [
        f"# TS-SatFire active-fire {purpose} event IDs.",
        f"# Upstream repository revision: {UPSTREAM_SHA}",
        "# Generated by scripts/materialize_splits.py; do not select by directory order.",
    ]
    path.write_text("\n".join([*header, *event_ids, ""]), encoding="utf-8")


def read_manifest(path: Path) -> list[str]:
    if not path.is_file():
        raise FileNotFoundError(f"Expected split manifest is missing: {path}")
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]


def assert_existing_manifests(expected: dict[str, list[str]]) -> None:
    mismatches = []
    for filename, expected_ids in expected.items():
        path = SPLIT_DIR / filename
        actual_ids = read_manifest(path)
        if actual_ids != expected_ids:
            unexpected = sorted(set(actual_ids) - set(expected_ids))
            missing = sorted(set(expected_ids) - set(actual_ids))
            mismatches.append(
                f"{filename}: expected {len(expected_ids)}, found "
                f"{len(actual_ids)}, unexpected={unexpected[:5]}, "
                f"missing={missing[:5]}"
            )
    if mismatches:
        raise ValueError(
            "Checked-in split manifests do not match the pinned upstream "
            "materializer. Resolve the event-to-scene mapping before training:\n"
            + "\n".join(mismatches)
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate sources without writing manifests.")
    args = parser.parse_args()

    source_ids = load_train_source_ids()
    validation = sorted(VALIDATION_IDS, key=_id_sort_key)
    training = [event_id for event_id in source_ids if event_id not in set(validation)]
    expected = {
        "train_event_ids.txt": training,
        "validation_event_ids.txt": validation,
        "test_event_ids.txt": list(ACTIVE_FIRE_TEST_IDS),
    }
    if set(training) & set(validation) or set(training) & set(ACTIVE_FIRE_TEST_IDS):
        raise ValueError("The pinned event partition is not disjoint.")
    if args.check:
        assert_existing_manifests(expected)
        print(f"Validated {len(training)} train, {len(validation)} validation, {len(ACTIVE_FIRE_TEST_IDS)} test events.")
        return

    SPLIT_DIR.mkdir(exist_ok=True)
    write_manifest(SPLIT_DIR / "train_event_ids.txt", expected["train_event_ids.txt"], "training")
    write_manifest(SPLIT_DIR / "validation_event_ids.txt", expected["validation_event_ids.txt"], "validation")
    write_manifest(SPLIT_DIR / "test_event_ids.txt", expected["test_event_ids.txt"], "test")
    print(f"Wrote {len(training)} train, {len(validation)} validation, {len(ACTIVE_FIRE_TEST_IDS)} test events to {SPLIT_DIR}.")


if __name__ == "__main__":
    main()
