#!/usr/bin/env python3
"""Materialize the pinned official TS-SatFire active-fire event partition.

The official generator at the pinned upstream revision builds training events
from the 2017–2020 ROI CSVs minus 13 validation IDs, and names 17 active-fire
test events.  This script makes that implicit logic inspectable and versioned.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ROI_DIR = PROJECT_ROOT / "roi"
SPLIT_DIR = PROJECT_ROOT / "splits"
UPSTREAM_SHA = "da7573219967edfe17e317310b66fd8a913f4a2e"

VALIDATION_IDS = (
    "20568194", "20701026", "20562846", "20700973", "24462610", "24462788",
    "24462753", "24103571", "21998313", "21751303", "22141596", "21999381",
    "22712904",
)
ACTIVE_FIRE_TEST_IDS = (
    "elephant_hill_fire", "eagle_bluff_fire", "double_creek_fire", "sparks_lake_fire",
    "lytton_fire", "chuckegg_creek_fire", "swedish_fire", "sydney_fire", "thomas_fire",
    "tubbs_fire", "carr_fire", "camp_fire", "creek_fire", "blue_ridge_fire",
    "dixie_fire", "mosquito_fire", "calfcanyon_fire",
)


def _id_sort_key(value: str) -> tuple[int, str]:
    return (0, f"{int(value):012d}") if value.isdigit() else (1, value)


def load_train_source_ids() -> list[str]:
    ids: list[str] = []
    for year in ("2017", "2018", "2019", "2020"):
        source = ROI_DIR / f"us_fire_{year}_out_new.csv"
        if not source.is_file():
            raise FileNotFoundError(f"Required official ROI source is missing: {source}")
        with source.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if "Id" not in (reader.fieldnames or []):
                raise ValueError(f"ROI source lacks the 'Id' column: {source}")
            ids.extend(row["Id"].strip() for row in reader if row["Id"].strip())
    if len(ids) != len(set(ids)):
        raise ValueError("The 2017–2020 ROI sources contain duplicate event IDs.")
    missing_validation = sorted(set(VALIDATION_IDS) - set(ids))
    if missing_validation:
        raise ValueError(f"Validation IDs absent from local ROI files: {missing_validation}")
    return sorted(ids, key=_id_sort_key)


def write_manifest(path: Path, event_ids: tuple[str, ...] | list[str], purpose: str) -> None:
    header = [
        f"# TS-SatFire active-fire {purpose} event IDs.",
        f"# Upstream repository revision: {UPSTREAM_SHA}",
        "# Generated by scripts/materialize_splits.py; do not select by directory order.",
    ]
    path.write_text("\n".join([*header, *event_ids, ""]), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate sources without writing manifests.")
    args = parser.parse_args()

    source_ids = load_train_source_ids()
    validation = sorted(VALIDATION_IDS, key=_id_sort_key)
    training = [event_id for event_id in source_ids if event_id not in set(validation)]
    if set(training) & set(validation) or set(training) & set(ACTIVE_FIRE_TEST_IDS):
        raise ValueError("The pinned event partition is not disjoint.")
    if args.check:
        print(f"Validated {len(training)} train, {len(validation)} validation, {len(ACTIVE_FIRE_TEST_IDS)} test events.")
        return

    SPLIT_DIR.mkdir(exist_ok=True)
    write_manifest(SPLIT_DIR / "train_event_ids.txt", training, "training")
    write_manifest(SPLIT_DIR / "validation_event_ids.txt", validation, "validation")
    write_manifest(SPLIT_DIR / "test_event_ids.txt", list(ACTIVE_FIRE_TEST_IDS), "test")
    print(f"Wrote {len(training)} train, {len(validation)} validation, {len(ACTIVE_FIRE_TEST_IDS)} test events to {SPLIT_DIR}.")


if __name__ == "__main__":
    main()
